services:
    forumhulp.cronstatus.listener:
        class: forumhulp\cronstatus\event\listener
        arguments:
            - @config
            - @controller.helper
            - @user
            - @template
            - @dbal.conn
            - @cron.manager
            - @dispatcher
        tags:
            - { name: event.listener }
